name: AutoTests (Push)
run-name: ${{ github.actor }} passed the tests ♥
on: [push]
jobs:

  run-tests:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Execute Gradle Test
        run: ./gradlew test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: '**/build/test-results/test/TEST*.xml'
          reporter: java-junit
          fail-on-error: true

      - name: send false message
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              Тесты не пройдены. (Тесты были запущены в автоматическом режиме)
      - name: send true message
        uses: appleboy/telegram-action@master
        if: success()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
              Тесты пройдены. (Тесты были запущены в автоматическом режиме)